version: "3.9"
services:
  backend:
    build: .
    container_name: todo-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tododb
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: secret
      API_SECRET: d8f7e2ad40a923155bc4a4d843f3a7522df3d4c0a43e6ecce8f3f6193dd58e60
      API_EXPIRATION_TIME: 10800000
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: todo-db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
